# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecko < Formula
  desc ""
  homepage ""
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/junchaw/ecko/releases/download/v0.1.5/ecko_v0.1.5_darwin_amd64.tar.gz"
      sha256 "8cf4833a67edd09539486d494b568ba524f8aa1e860918538bb3c365e85c8ca3"

      def install
        bin.install "ecko"
      end
    end
    on_arm do
      url "https://github.com/junchaw/ecko/releases/download/v0.1.5/ecko_v0.1.5_darwin_arm64.tar.gz"
      sha256 "adaa5a4496a330319faa9eeadfc66294d32c0664bf3e9813aac968c5064a2917"

      def install
        bin.install "ecko"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/junchaw/ecko/releases/download/v0.1.5/ecko_v0.1.5_linux_amd64.tar.gz"
        sha256 "6923588f0b16dfb2a821094517ef94ac09620b3acbbd9cc4a8e322adbc67c364"

        def install
          bin.install "ecko"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/junchaw/ecko/releases/download/v0.1.5/ecko_v0.1.5_linux_arm64.tar.gz"
        sha256 "5615ef8f4edef802b98c0f68c2897bb0726ad2e367bf0dff95c1235c18aa982b"

        def install
          bin.install "ecko"
        end
      end
    end
  end
end
