# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCf < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/junchaw/kubectl-cf/releases/download/v0.1.2/kubectl-cf_v0.1.2_darwin_amd64.tar.gz"
      sha256 "3415579165284b5033a11112f95bb36bc8f1cad5469889ca0e90f9abf0575fae"

      def install
        bin.install "kubectl-cf"
      end
    end
    on_arm do
      url "https://github.com/junchaw/kubectl-cf/releases/download/v0.1.2/kubectl-cf_v0.1.2_darwin_arm64.tar.gz"
      sha256 "4e5ac88936a6e0e98e01622a1ae1a629fc6dd3057aa77b46b799b731356eb2cf"

      def install
        bin.install "kubectl-cf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/junchaw/kubectl-cf/releases/download/v0.1.2/kubectl-cf_v0.1.2_linux_amd64.tar.gz"
        sha256 "27fd9f76b387fde639b8fad14c946e1bf3fe45875c0cdd012e3cddc4f7a53c1b"

        def install
          bin.install "kubectl-cf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/junchaw/kubectl-cf/releases/download/v0.1.2/kubectl-cf_v0.1.2_linux_arm64.tar.gz"
        sha256 "d08b64d8fc3d90d5e290fb9832483acd0767f4e65464f484012334a39f24446e"

        def install
          bin.install "kubectl-cf"
        end
      end
    end
  end
end
