# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubekraken < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/junchaw/kubekraken/releases/download/v0.1.2/kubekraken_v0.1.2_darwin_amd64.tar.gz"
      sha256 "a70ffc3be5be89b94bebbb827f7520159788f460f7e40e9637574069f4df7660"

      def install
        bin.install "kubekraken"
      end
    end
    on_arm do
      url "https://github.com/junchaw/kubekraken/releases/download/v0.1.2/kubekraken_v0.1.2_darwin_arm64.tar.gz"
      sha256 "ddcf06ad34cf0bae6b9725a4edfb79f8ef1bb4cc93a6f95337962bc78dd7d0d7"

      def install
        bin.install "kubekraken"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/junchaw/kubekraken/releases/download/v0.1.2/kubekraken_v0.1.2_linux_amd64.tar.gz"
        sha256 "d792ee7b3e9fd241bcb25f8de358fa39a39edffdcbe95c02e45a963421a287fd"

        def install
          bin.install "kubekraken"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/junchaw/kubekraken/releases/download/v0.1.2/kubekraken_v0.1.2_linux_arm64.tar.gz"
        sha256 "ccb328ba2d40743b751b41ab4a20f85e97e76e08ef77d45875466fb828de57b0"

        def install
          bin.install "kubekraken"
        end
      end
    end
  end
end
